### ISSUE TITLE
Issue while searching for multiple words & operators using Query string parameter

### ISSUE THREAD

**Issue by shekhar0603** [Matej4386/SP2019-search#6]
Hello @Matej4386 , search solution worked for me i.e using 'k' as search parameter.

But it only worked for single word : Ex : ?k=Capacity

When I searched for multiple words using query string parameter i.e. : ?k=Capacity widget , it didn't gave any search result.

So I tried using Search Box, it gave me results for ?k=Capacity widget. as shown below:

![image](https://user-images.githubusercontent.com/39938835/114875363-da13c880-9e1a-11eb-9ae7-5e40cb610849.png)

Also query string is not working for any Boolean operator but search box is working ex: ?k=Capacity NEAR filters.

![image](https://user-images.githubusercontent.com/39938835/114875432-e6982100-9e1a-11eb-8a1b-6846ce02d1f0.png)

If you can please look into this issue and make Boolean operator and multiple words to be searched using query string work.

Thanks,
Shekhar

**Comment by Matej4386** [comment]
Hello @shekhar0603, really sorry for delay - a lot of work. ANd sorry for bug :-( I just forgott one small function decodeURIComponent. The problem is that if you put something with multiple words it will be stored in variable coded (for example capacity widget will be stored as capacity%20widget) - due to this search did not work. So just change this:
const searchK: string = UrlHelper.getQueryStringParam('k', null);
    if (searchK) {
        queryKeywords = searchK;
    }

to this:
const searchK: string = UrlHelper.getQueryStringParam('k', null);
    if (searchK) {
        queryKeywords = decodeURIComponent(searchK);
    }

I have updated code. Thank you for using this solution and comments.
